### ISSUE TITLE
Licensing is invalid

### ISSUE THREAD

**Issue by sigmavirus24** [avinassh/status#5]
You cannot copy a file wholesale from another project with copyright and licensing written one way and then add your own license claiming copyright for something you did not implement. The License must reflect the actual copyright (Tom Christie)

**Comment by avinassh** [comment]
Thank you for bringing this to my attention. So what should be the right way to fix it? Replacing this repo's license with DRF's license will do?

only code here mine is `setup.py`

**Comment by sigmavirus24** [comment]
Right you would copy DRF's license and then you could tack your name on a new line for the setup.py.

**Comment by avinassh** [comment]
#6 this sounds fine?

**Comment by gdude2002** [comment]
Does the MIT allow dual-licensing?

EDIT: Actually, the original license doesn't, so that's kind of moot, isn't it..

**Comment by avinassh** [comment]
> EDIT: Actually, the original license doesn't, so that's kind of moot, isn't it..

So I cannot have original license for `status.py` and my own for others?

**Comment by gdude2002** [comment]
If you want to be in the clear I would suggest contacting the original license holder.

I'm not a lawyer, though - just a detail that caught my eye, something to check on. Sigma probably has a better idea of that than I do.

**Comment by avinassh** [comment]
I already did! [tweeted out to him](https://twitter.com/iavins/status/654730433230344194) just few seconds ago.

shit, I made a big fuck up. I should have given some thought into licensing. I usually fork and continue with the original license. And I think I should have included full license in `status.py` file.

**Comment by carltongibson** [comment]
#6 adds the originally copy right and disclaimer, as per the original licence, so it should be good.

**Comment by sigmavirus24** [comment]
@carltongibson "should" is a rats nest when it comes to copyright law and licensing. It's not clear to me what DRF's original license is and as such it may or may not be possible to dual license. @avinassh you're better off getting @ryansb to agree to change the license to be conformant with DRF and @ryansb should actually have sent his contribution to DRF in the first place.

**Comment by carltongibson** [comment]
@sigmavirus24 Indeed. :-) But it **seems** pretty liberal and met by #6. Tom has been told and can object if he doesn't agree. 

https://github.com/tomchristie/django-rest-framework/blob/master/LICENSE.md

**Comment by gdude2002** [comment]
Eh, wouldn't it be better to not apply a possibly-incorrect license until we're sure it's okay?

Besides, @sigmavirus24 is correct, one would have to wait for @ryansb to agree to any license changes here.

**Comment by ryansb** [comment]
Commented on #6 to accept the change in license so at the very least my consent isn't blocking resolving this.

**Comment by avinassh** [comment]
Thanks @ryansb 

I will wait to hear from Tom. And I think I cannot have dual licenses. 

> Tom has been told and can object if he doesn't agree.

Well, in this matter, I will ask for permission instead of asking forgiveness. (well I already committed a mistake, let me not repeat it ;))

I am reading upon OSS licensing. And also if I keep Tom's license, can I accept PRs on `status.py` file later?

**Comment by gdude2002** [comment]
I assume that said PRs would be contributed under the understanding that that file is under that license. Since this is a repackaging of that file though, Sigma is right once again - the PR should really be aimed at DRF.

**Comment by ryansb** [comment]
First, I am not a lawyer. 

The Free Software Foundation has a useful guide for choosing and understanding licenses [here](https://www.gnu.org/licenses/license-recommendations.html)

I often reference the Software Freedom Law Center's Legal Primer for both practical and academic purposes (highly recommended) [here](https://www.softwarefreedom.org/resources/2008/foss-primer.html#x1-60002.2)

https://tldrlegal.com/ is quite a useful resource for comparing the various FOSS licenses out there once you have some context.

To get ahold of actual lawyers/advisors who help FOSS projects, you can reach out to the FSF, SFLC, and OSI at:
licensing@fsf.org
help@softwarefreedom.org
license-discuss@opensource.org

**Comment by sigmavirus24** [comment]
Seconding @ryansb's disclaimer.

@avinassh for now, any PRs that are made to status.py should be made to DRF and then pulled in here. Any new development done here (new APIs, modules, etc.) would then be your copyright but you should not dual license then either. You and (most importantly) your users would be best served by having one uniform license for the entire project and distribution. Until you start adding novel ideas, all PRs should be sent to DRF for them to accept/reject and then you should update this module as a result before making a new release. You're describing this as a repackaging of one submodule in DRF and as such you should develop this package that way.

**Comment by avinassh** [comment]
I really don't mind having Tom's copyright and `LICENSE`. I think cannot have dual licenses too. And I am fine with that. 

But what I want to know is, if there is any way, which is okay with Tom and OSS Licenses that let me accept PR on `status.py`. Or else there will be no point of this project.

> I assume that said PRs would be contributed under the understanding that that file is under that license. Since this is a repackaging of that file though, Sigma is right once again - the PR should really be aimed at DRF.

So one cannot send a PR to a fork? That is... seems not right :/

**Comment by sigmavirus24** [comment]
> So one cannot send a PR to a fork? That is... seems not right :/

Someone can, whether or not you should accept it is your choice. But then you need to stop advertising this as a repackaging of DRF's submodule and make sure that people understand this is a fork of that particular submodule and not of DRF as a whole.

**Comment by gdude2002** [comment]
I'm sure PRs would be permitted by the license, but that logically makes no sense. It would be better to have PRs on DRF's copy because having two separate versions will cause fragmentation and merging headaches.

Of course, you could declare this a fork rather than a repackaging and take it in your own direction too, as Sigma has said.

**Comment by avinassh** [comment]
> But then you need to stop advertising this as a repackaging of DRF's submodule and make sure 
> that people understand this is a fork of that particular submodule and not of DRF as a whole.
> 
> Of course, you could declare this a fork rather than a repackaging and take it in your own direction too, as Sigma has said.

So, I need to mention that: 
- This is a fork and independently maintained
- And it is not a submodule of DRF
- And has nothing do with DRF

Just to clarify, it was not my intent to 'advertise' this as DRF's submodule. I wanted to give credit, since I copied from it.

**Comment by sigmavirus24** [comment]
So then this is a simple fork.

It maintains the same license. 

You can accept PRs and you might do the reasonable and preferable thing and offer any contributions you receive back to DRF.

**Comment by avinassh** [comment]
Btw Tom [replied](https://twitter.com/_tomchristie/status/654742934311473152) and said he is okay with #6. However I don't like dual licensing and I have updated the PR #6:
1. No dual licensing. I hate dual licenses and neither I am allowed to have it since it doesn't comply with original Tom's license. 
2. I have added copyright notice for every other file than `status.py`
3. I have updated the `CREDITS` section to make clear that it is not a submodule and is a fork. 

Let me know what do you guys think

**Comment by avinassh** [comment]
Okay guys, going ahead with the merge. Let me know if there's anything. Thanks!
